### ISSUE TITLE
Add and document "Project Management" features to the repository

### ISSUE THREAD

**Issue by aldrichtr** [aldrichtr/tangld#22]
## Overview
Github has so many awesome project management features.  Ensure that they are used efficiently and uniformly throughout the project.

## Tasks
- [ ] Develop and document a set of labels for use in issues, PRs, discussions, etc
- [ ] Develop and document a set of project boards to organize the work
- [ ] Develop and document a set of issue templates
- [ ] #1
